CREATE DATABASE AccountManagement;
GO

USE AccountManagement;
GO

CREATE TABLE UserDetails (
	 Id UNIQUEIDENTIFIER NOT NULL,
	 UserName VARCHAR(50) NOT NULL,
	 [Password] VARCHAR(50),
	 Firstname VARCHAR(50),
	 LastName VARCHAR(50),
	 Email VARCHAR(50),
	 PhoneNumber VARCHAR(20),
	 IsActive BIT DEFAULT 0,
	 CreatedAt DATETIME DEFAULT GETUTCDATE(),
	 UpdatedAt DATETIME,

	 CONSTRAINT PK_UserDetails_Id PRIMARY KEY CLUSTERED (Id),
	 CONSTRAINT UQ_UserDetails_Email UNIQUE (Email),
	 CONSTRAINT UQ_UserDetails_Phone UNIQUE (PhoneNumber)
 );

 SELECT * FROM UserDetails;

 DROP TABLE Accounts;

 CREATE TABLE Accounts (
	 Id UNIQUEIDENTIFIER NOT NULL,
	 [Name] VARCHAR(50) NOT NULL,
	 UserId UNIQUEIDENTIFIER NOT NULL,
	 IsActive BIT DEFAULT 0,
	 CreatedAt DATETIME DEFAULT GETUTCDATE(),
	 UpdatedAt DATETIME,

	 CONSTRAINT PK_Accounts_Id PRIMARY KEY CLUSTERED (Id),
	 CONSTRAINT FK_Accounts_UserDetails_Id FOREIGN KEY (UserId) REFERENCES UserDetails(Id)
	 ON DELETE CASCADE ON UPDATE CASCADE,
 );

 SELECT * FROM UserDetails; SELECT * FROM Accounts;

 CREATE TABLE PassBook (
	Id UNIQUEIDENTIFIER NOT NULL,
	Particular VARCHAR(100) NOT NULL,
	[Type] VARCHAR(2) NOT NULL,
	AccountId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	IsActice BIT DEFAULT 0,
	CreatedAt DATETIME DEFAULT GETUTCDATE(),
	UpdatedAt DATETIME,

	CONSTRAINT PK_PassBook_Id PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT FK_PassBook_UserDetails_Id FOREIGN KEY (AccountId) REFERENCES UserDetails (Id) 
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT FK_PassBook_Accounts_Id FOREIGN KEY (AccountId) REFERENCES Accounts (Id)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
 );

